// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cydajutrsdqajxohohpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5ZGFqdXRyc2RxYWp4b2hvaHB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzMDUzNzQsImV4cCI6MjA1NDg4MTM3NH0.WtrN-1hU70D4wcmX9pr2BBUv6gPh5XGla1FFyr5knM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);